### ISSUE TITLE
.IPA Files Won't Install in XCode Organizer

### ISSUE THREAD

**Issue by DerekStutsman** [rayh/xcode-hudson-plugin#4]
.ipa files generated by the plugin fail to install when dragged to the XCode Organizer.  They do, however, install correctly using iTunes.

The error given by XCode Organizer is:

"The Info.plist for application at /Users/derekstutsman/Desktop/Redacted_iPhone_1.0_r216_Adhoc_2010-10-29_11-30-57.ipa specifies a CFBundleExecutable of Redacted, which is not executable"

.ipa files generated using "Build and Archive" in XCode work fine.

I wonder if this is a switch on XCodeBuild that needs to be set?  Or some kind of permissions issue?

**Comment by rayh** [comment]
Can you rename the XCode generated .ipa to .zip, decompress it and then send me the file listing (no need to detail the contents of the .app).  It may be that your project requires files other than the Payload/YOURAPP.app

**Comment by DerekStutsman** [comment]
I found the difference between the two.

On the Hudson-built IPA file, there is a 25KB "CodeResources" file in the .app bundle.  
In the "Build and Archive" IPA file, there is a CodeResources symlink in the app bundle.  This symlink points to the CodeResources file inside the _CodeSignature folder.

I am betting that the symlink is getting "flattened" during the IPA generation - probably there is a switch to preserve them but I am just guessing.

**Comment by DerekStutsman** [comment]
A little more detail...

It looks like Hudson's FilePath::copyRecursiveTo ultimately uses File::copyTo without any flags.

That's causing the Symlink to be followed during the IPA creation.

We might have to do our own version of copyRecursiveTo that includes the appropriate NOFOLLOW_LINKS param when doing the file copies.

http://download.oracle.com/javase/tutorial/essential/io/copy.html

**Comment by rayh** [comment]
Could you try re-compressing the hudson generated .ipa with the symlinks flattened?  If you can install that .ipa, then I think you are on to something.  

The FilePath stuff may execute on a different machine.  I'm not sure if there is a way of executing Java IO stuff directly on the remote machine in a hudson way.  Anyway, check the above first and we'll take it from there.

**Comment by DerekStutsman** [comment]
I had to upgrade this issue from "annoyance" to "blocking problem" because I found out iTunesConnect doesn't like the IPAs either.

For now I have disabled the "Build IPA" checkbox and instead I'm using the following script step.  This also archives the symbol files with each build.

rm -rf Payload
mkdir Payload
cp -Rp YOURAPPNAME.app Payload
zip -r -T -y YOURAPPNAME.ipa Payload
zip -r -T -y YOURAPPNAME_Symbols.zip *.dSYM

**Comment by DerekStutsman** [comment]
You can, of course, use environment variables to put the job name, build number, etc into the filename.

**Comment by rayh** [comment]
The current version in git (which I haven't built a release for yet) will name the artifact after the configuration (e.g. Release) and the build number.

As for the zip-building, it seems to work fine for me.  Could you create a basic project that fails so that I have something to test against?

**Comment by DerekStutsman** [comment]
Well it does work - the .IPAs generated by the plugin will work in iTunes.  But in my experience they don't work in Organizer or for App Store submissions.

I don't think it has any project affinity as all the jobs exhibit the same behavior here.

**Comment by rayh** [comment]
Gotcha.  I'll try and take a look on Monday

**Comment by rayh** [comment]
I've taken your suggestions and put them into the plugin.  Could you try this build and let me know how it goes: http://github.com/downloads/rayh/xcode-hudson-plugin/xcode-0.1.21.hpi

**Comment by lucasweb78** [comment]
Did this ever get resolved. I'm having the same problem described above using xcode-0.1.21.hpi.

Looking at the contents of the ipa generated by the plugin vs the ipa generated directly from xcode it appears that the binary inside the ipa is not executable when generated via the plugin but it is when generated by xcode (see below):

Exploded IPA generated by Xcode

drwxr-xr-x  10 lucasr  staff    340 Jul 11 14:30 .
drwxr-xr-x   3 lucasr  staff    102 Jul 11 14:30 ..
lrwxr-xr-x   1 lucasr  staff     28 Jul 11 14:31 CodeResources -> _CodeSignature/CodeResources
-rw-r--r--@  1 lucasr  staff   1098 Jul 11 14:30 Info.plist
-rwxr-xr-x@  1 lucasr  staff  43968 Jul 11 14:30 JenkinsIOSExample
-rw-r--r--@  1 lucasr  staff      8 Jul 11 14:30 PkgInfo
-rw-r--r--@  1 lucasr  staff    485 Jul 11 14:30 ResourceRules.plist
drwxr-xr-x   3 lucasr  staff    102 Jul 11 14:30 _CodeSignature
-rw-r--r--@  1 lucasr  staff   7208 Jul 11 13:42 embedded.mobileprovision
drwxr-xr-x   5 lucasr  staff    170 Jul 11 14:30 en.lproj

Exploded IPA generated by plugin

drwxr-xr-x  10 lucasr  staff    340 Jul 11 13:49 .
drwxr-xr-x   3 lucasr  staff    102 Jul 11 13:49 ..
-rw-r--r--@  1 lucasr  staff    964 Jul 11 13:49 CodeResources
-rw-r--r--@  1 lucasr  staff   1106 Jul 11 13:49 Info.plist
-rw-r--r--@  1 lucasr  staff  52576 Jul 11 13:49 JenkinsIOSExample
-rw-r--r--@  1 lucasr  staff      8 Jul 11 13:49 PkgInfo
-rw-r--r--@  1 lucasr  staff    485 Jul 11 13:49 ResourceRules.plist
drwxr-xr-x   3 lucasr  staff    102 Jul 11 13:49 _CodeSignature
-rw-r--r--@  1 lucasr  staff   7229 Jul 11 13:49 embedded.mobileprovision
drwxr-xr-x   5 lucasr  staff    170 Jul 11 13:49 en.lproj

**Comment by rayh** [comment]
What version of the xcode tools are you using?  Under the hood, it just uses xcodebuild to build .app as well as the .ipa, so the output /should/ be the same.  However, It might be an XCode 4/4.2 difference.

**Comment by lucasweb78** [comment]
I'm using Xcode Version 4.0.2.

**Comment by rayh** [comment]
Have you tried building from source?  My snapshot building is currently down as I dont have a build box.

**Comment by lucasweb78** [comment]
I haven't. I need to get an environment set up with Maven. I'll try that tomorrow.

**Comment by DerekStutsman** [comment]
I haven't tried building the latest - I'm not a Java person and didn't have time to mess with it.
I just did the shell scripts I referenced above, which worked.

**Comment by lucasweb78** [comment]
I built from plugin using the latest version of the source code and it works fine. The IPA file is generated correctly with both the symlinks and permissions set correctly and I am able to load the IPA file onto the device via Xcode Organizer.

Thanks for your help

**Comment by rayh** [comment]
Yay!

I will update the snapshot on my site

Ray

On 13 July 2011 07:29, lucasweb78
reply@reply.github.com
wrote:

> I built from plugin using the latest version of the source code and it works fine. The IPA file is generated correctly with both the symlinks and permissions set correctly and I am able to load the IPA file onto the device via Xcode Organizer.
> 
> Thanks for your help
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rayh/xcode-hudson-plugin/issues/4#issuecomment-1558012

## 

## Ray Hilton

m: 0430 484 708
w: http://rayh.com.au

**Comment by DerekStutsman** [comment]
Thanks Ray!  I look forward to the updated DL.

**Comment by rayh** [comment]
Should be updated now

On 21 July 2011 09:00, DerekStutsman
reply@reply.github.com
wrote:

> Thanks Ray!  I look forward to the updated DL.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rayh/xcode-hudson-plugin/issues/4#issuecomment-1619829

## 

## Ray Hilton

m: 0430 484 708
w: http://rayh.com.au
