### ISSUE TITLE
Zipping of *.dSYM fails (+fix)

### ISSUE THREAD

**Issue by vtim** [rayh/xcode-hudson-plugin#8]
For some reason, zipping the dSYM failed on my machine:

[Debug-iphoneos] $ zip -r -T -y "ad-Debug-Build and Archive AD-5-dSYM.zip" *.dSYM
    zip warning: name not matched: *.dSYM

zip error: Nothing to do! (try: zip -r -T -y ad-Debug-Build and Archive AD-5-dSYM.zip . -i *.dSYM)
Failed to zip *.dSYM into ad-Debug-Build and Archive AD-5-dSYM.zip

In XCodeBuilder.jar, changing `"*.dSYM"` to `app.getBaseName() + ".app.dSYM"` fixed it:

``` java
// also zip up the symbols, if present
// returnCode = launcher.launch().envs(envs).stdout(listener).pwd(buildDirectory).cmds("zip", "-r", "-T", "-y", baseName + "-dSYM.zip", "*.dSYM").join();
returnCode = launcher.launch().envs(envs).stdout(listener).pwd(buildDirectory).cmds("zip", "-r", "-T", "-y", baseName + "-dSYM.zip", app.getBaseName() + ".app.dSYM").join();
```

**Comment by rayh** [comment]
Would you mind forking, making the changes, and then issuing a pull
request?  I don't have a Java environment setup at the moment, so it
would take me a while to get around to this.

Thanks!

On 9 September 2011 20:03, vtim
reply@reply.github.com
wrote:

> For some reason, zipping the dSYM failed on my machine:
> 
> [Debug-iphoneos] $ zip -r -T -y "ad-Debug-Build and Archive AD-5-dSYM.zip" *.dSYM
>        zip warning: name not matched: *.dSYM
> 
> zip error: Nothing to do! (try: zip -r -T -y ad-Debug-Build and Archive AD-5-dSYM.zip . -i *.dSYM)
> Failed to zip *.dSYM into ad-Debug-Build and Archive AD-5-dSYM.zip
> 
> In XCodeBuilder.jar, changing `"*.dSYM"` to `app.getBaseName() + ".app.dSYM"` fixed it:
> 
> ``` java
> // also zip up the symbols, if present
> // returnCode = launcher.launch().envs(envs).stdout(listener).pwd(buildDirectory).cmds("zip", "-r", "-T", "-y", baseName + "-dSYM.zip", "*.dSYM").join();
> returnCode = launcher.launch().envs(envs).stdout(listener).pwd(buildDirectory).cmds("zip", "-r", "-T", "-y", baseName + "-dSYM.zip", app.getBaseName() + ".app.dSYM").join();
> ```
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rayh/xcode-hudson-plugin/issues/8

## 

## Ray Hilton

m: 0430 484 708
w: http://rayh.com.au
